#!/usr/bin/env python3
"""Embed offline UI assets in the host binary (no runtime working-directory dependency)."""
from pathlib import Path
import argparse
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument("--output",type=Path)
args=parser.parse_args()
root=Path(__file__).resolve().parents[1]
parts=['// Generated by tools/embed_web.py; edit web/ files.\n#pragma once\n']
for symbol,name in [('web_page','index.html'),('web_js','app.js'),('web_css','styles.css')]:
    text=(root/'web'/name).read_text()
    assert ')BKDSWEB"' not in text
    parts.append(f'static const char {symbol}[]=R"BKDSWEB({text})BKDSWEB";\n')
output=args.output or root/'src/link/web_page.hpp'
output.parent.mkdir(parents=True,exist_ok=True)
output.write_text(''.join(parts))
