"""Generate portable C++ metadata from the frozen wire catalog."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'metadata/controls.json').read_text())
s=['// Generated by tools/generate_link_catalog.py; edit metadata/controls.json.','#pragma once','#include <array>','#include <cstdint>','namespace bkds::link {','struct Control { uint8_t id; const char* name; bool mono; int bank; };',f'inline constexpr std::array<Control,{len(data["controls"])}> Controls = {{{{']
for c in data['controls']:
    s.append('    {'+str(c['id'])+','+json.dumps(c['name'])+','+str(c['states']==1).lower()+','+str(c['shared_color_bank'] if c['shared_color_bank'] is not None else -1)+'},')
s+=['}};','inline const Control* control(unsigned id) { for(const auto& c:Controls) if(c.id==id) return &c; return nullptr; }','}']
(root/'src/link/catalog.hpp').write_text('\n'.join(s)+'\n')
